### ISSUE TITLE
Does not download Halo: Combat Evolved Assets titleId: 4d53084c

### ISSUE THREAD

**Issue by JaviJJ117** [XboxUnity/AuroraAssetEditor#12]
Hello, I have seen that Aurora Asset Editor cannot download the Halo: Combat Evolved Assets neither by searching by titleId nor by title and from Aurora on Xbox 360 they can be downloaded through a default.xex with that titleId, I know that the information is In the API I have managed to obtain the name title through the titleId, not with the main application, it has been with a small program that I made using the XboxAssetDownloader.cs class to obtain all the Ids, I have obtained 8035 different Ids with the name title, yes you need the list I can share it with you, I have made another small program using the titleId list and the same class "XboxAssetDownloader.cs" to download all the images in the aurora import format, but it seems that those of Halo: Combat Evolved and some more are inaccessible at the moment, by decrypting Aurora.xex with xextool you can see how the Assets are downloaded and apply it to Aurora Asset Editor to also be able to download the Halo: Combat Evolved Assets, I think this affects all backward compatible games on the Marketplace

**Comment by JaviJJ117** [comment]
I don't understand, it seems that they are not downloaded from the same site Monster Madness shows 13 images in AuroraAssetEditor and in Aurora I can up to 20 on the marketplace web, up to 26 are seen, they are the same ones from Aurora and these are seen with errors, even on the web they are also repeated some, but in the 13 Aurora Asset Editor ones they do not have the error, in all cases I am using the en-US locale, it seems that in some cases the same elements that would be found on the web and in Aurora are not found, In this case it is beneficial not to have repeated images or images with errors.

**Comment by Swizzy** [comment]
@JaviJJ117 can you test if this works for you now?; https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.4.2

**Comment by JaviJJ117** [comment]
> @JaviJJ117 can you test if this works for you now?; https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.4.2

Hello, I've tried it, and the download of assets for backward-compatible games has been fixed. Now, it's also downloading the 26 images for Monster Madness, as well as the icons and banners for XBLIG. The latter wasn't downloading in version 1.4.1 either. Thanks to everyone for the quick resolution.

**Comment by JaviJJ117** [comment]
> @JaviJJ117 can you test if this works for you now?; https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.4.2

@Swizzy, I have done more tests and it seems that from the main application you see multiple banners in some backward compatible games, I have seen that in the first ones that were uploaded such as Halo, Burnout 3 and Gta San Andreas: 54540841 happens, in this one you can even see a ninja Gaiden Black banner, in the XBLIG it seems that the banner is also seen twice, for the test I did before I had used the new XboxAssetDownloader.cs class with the small program that I created to download all the assets from a list of TitleId and only downloaded a banner, the problem did not occur, but it seems that using the Aurora Asset Editor application they are multiplied.

**Comment by jrobiche** [comment]
Personally, I don't believe the duplicates are an issue because it accurately represents the assets defined in the xbox catalog (https://catalog.xboxlive.com)

Side note:
Technically the information is pulled from http://catalog-cdn.xboxlive.com which is a non-https version of the catalog. This should probably be reverted back to https://catalog.xbox.com now that TLS 1.1/1.2 support was added (see https://github.com/XboxUnity/AuroraAssetEditor/pull/5)

For example let's look at the en-US response for Halo: Combat Evolved (4d53084c). If you open the link
https://catalog.xboxlive.com/Catalog/Catalog.asmx/Query?methodName=FindGames&Names=Locale&Values=en-US&Names=LegalLocale&Values=en-US&Names=Store&Values=1&Names=PageSize&Values=100&Names=PageNum&Values=1&Names=DetailView&Values=5&Names=OfferFilterLevel&Values=1&Names=MediaIds&Values=66acd000-77fe-1000-9115-d8024d53084c&Names=UserTypes&Values=2&Names=MediaTypes&Values=1&Names=MediaTypes&Values=21&Names=MediaTypes&Values=23&Names=MediaTypes&Values=37&Names=MediaTypes&Values=46
in a browser, you should see an XML file.
Banners have a `live:relationshipType` of `27`, so if you search for `<live:relationshipType>27</live:relationshipType>` you should see 13 results. This means that Halo: Combat Evolved actually does have 13 different banners defined and because most banners have a different `live:fileUrl` there is no way of knowing if two banners look the same without downloading them.

Same for GTA San Andreas (54540841). If you go to
https://catalog.xboxlive.com/Catalog/Catalog.asmx/Query?methodName=FindGames&Names=Locale&Values=en-US&Names=LegalLocale&Values=en-US&Names=Store&Values=1&Names=PageSize&Values=100&Names=PageNum&Values=1&Names=DetailView&Values=5&Names=OfferFilterLevel&Values=1&Names=MediaIds&Values=66acd000-77fe-1000-9115-d80254540841&Names=UserTypes&Values=2&Names=MediaTypes&Values=1&Names=MediaTypes&Values=21&Names=MediaTypes&Values=23&Names=MediaTypes&Values=37&Names=MediaTypes&Values=46
and search for `<live:relationshipType>27</live:relationshipType>` there should be 5 results.
The last result is a banner for Ninja Gaiden Black, but this is an error on Microsoft's side.

**Comment by JaviJJ117** [comment]
@jrobiche I also thought it could be because they were available in the market place and that's why they are shown, in that case I don't consider it to be a problem either.
Would it be possible to make Aurora Asset Editor download the TitleName, Description, Publisher, Developer, LiveRating, LiveRaters, ReleaseDate, GenereFlag, ContentFlags, GameCapsOnline, GameCapsOffline and GameCapsFlags information in text?
It would be fantastic to do that, so I could download that information for all games and regions through the PC.
At the moment I can only use Aurora and downloading all regions like this will take a long time.

**Comment by jrobiche** [comment]
I feel like that functionality would be outside the scope of this application

**Comment by JaviJJ117** [comment]
@jrobiche But I imagine that it would be possible to extract the necessary code from Aurora and integrate it into XboxAssetDownloader.cs and create a simple application that uses that class and runs in the terminal doing the function without having to configure all the necessary graphical interface.

**Comment by Swizzy** [comment]
> @jrobiche But I imagine that it would be possible to extract the necessary code from Aurora and integrate it into XboxAssetDownloader.cs and create a simple application that uses that class and runs in the terminal doing the function without having to configure all the necessary graphical interface.
> I imagine that it can be carried out from the function obtain the title from the titleId.

Yes, it's possible but you'll have to do that on your own.

**Comment by JaviJJ117** [comment]
@Swizzy Ok, I'm going to start working on it. I don't have any programming knowledge, but with the help of Chat GPT I think I can do it. I'll let you know if I manage to do it.
The Issue about Halo Combat Evolved is already resolved, I don't know if you want to close the issue now or after publishing version 1.4.2, I will leave it in your hands, thanks again for the quick resolution.

**Comment by JaviJJ117** [comment]
@Swizzy I have managed to download the descriptions, I suppose that the rest of the data can be obtained in the same way, I am going to continue working on it,
To obtain the description I have done the following:
1st I added a Description property to the XboxTitleInfo class:
public class XboxTitleInfo {
         public enum XboxAssetType {
             Icon,
             banner,
             Background,
             Screenshot
         }

         public string Title { get; privateset; }

         // I added this string to get and assign the description
         public string Description { get; privateset; }

         public string TitleId { get; privateset; }

         public string Locale { get; privateset; }

         public XboxAssetInfo[] AssetsInfo { get; privateset; }


2º I modified the ParseXml method to extract and assign the description:
private static void ParseXml(Stream xmlData, XboxTitleInfo titleInfo)
{
     XboxAssetDownloader.SendStatusChanged("Parsing Title/Asset info...");
     var ret = new List<XboxAssetInfo>();
     using (var xml = XmlReader.Create(xmlData))
     {
         while (xml.Read())
         {
             if (!xml.IsStartElement())
                 continue;

             if (xml.Name.ToLower() == "live:fulltitle")
             {
                 xml.Read();
                 titleInfo.Title = xml.Value;
                 continue;
             }

             // I added this code to get and assign the description
             if (xml.Name.ToLower() == "live:description")
             {
                 xml.Read();
                 titleInfo.Description = xml.Value;
                 continue;
             }

**Comment by JaviJJ117** [comment]
@Swizzy I have managed to download the descriptions, I suppose that the rest of the data can be obtained in the same way, I am going to continue working on it,
To obtain the description I have done the following:
1st I added a Description property to the XboxTitleInfo class:

public class XboxTitleInfo {
         public enum XboxAssetType {
             Icon,
             banner,
             Background,
             Screenshot
         }

         public string Title { get; privateset; }

         // I added this string to get and assign the description
         public string Description { get; privateset; }

         public string TitleId { get; privateset; }

         public string Locale { get; privateset; }

         public XboxAssetInfo[] AssetsInfo { get; privateset; }


2º I modified the ParseXml method to extract and assign the description:

private static void ParseXml(Stream xmlData, XboxTitleInfo titleInfo)
{
     XboxAssetDownloader.SendStatusChanged("Parsing Title/Asset info...");
     var ret = new List<XboxAssetInfo>();
     using (var xml = XmlReader.Create(xmlData))
     {
         while (xml.Read())
         {
             if (!xml.IsStartElement())
                 continue;

             if (xml.Name.ToLower() == "live:fulltitle")
             {
                 xml.Read();
                 titleInfo.Title = xml.Value;
                 continue;
             }

             // I added this code to get and assign the description
             if (xml.Name.ToLower() == "live:description")
             {
                 xml.Read();
                 titleInfo.Description = xml.Value;
                 continue;
             `}```

**Comment by JaviJJ117** [comment]
@Swizzy I have managed to download the descriptions, I suppose that the rest of the data can be obtained in the same way, I am going to continue working on it,
To obtain the description I have done the following:
1st I added a Description property to the XboxTitleInfo class:

```
public class XboxTitleInfo {
         public enum XboxAssetType {
             Icon,
             banner,
             Background,
             Screenshot
         }

         public string Title { get; privateset; }

         // I added this string to get and assign the description
         public string Description { get; privateset; }

         public string TitleId { get; privateset; }

         public string Locale { get; privateset; }

         public XboxAssetInfo[] AssetsInfo { get; privateset; }
```


2º I modified the ParseXml method to extract and assign the description:

```
private static void ParseXml(Stream xmlData, XboxTitleInfo titleInfo)
{
     XboxAssetDownloader.SendStatusChanged("Parsing Title/Asset info...");
     var ret = new List<XboxAssetInfo>();
     using (var xml = XmlReader.Create(xmlData))
     {
         while (xml.Read())
         {
             if (!xml.IsStartElement())
                 continue;

             if (xml.Name.ToLower() == "live:fulltitle")
             {
                 xml.Read();
                 titleInfo.Title = xml.Value;
                 continue;
             }

             // I added this code to get and assign the description
             if (xml.Name.ToLower() == "live:description")
             {
                 xml.Read();
                 titleInfo.Description = xml.Value;
                 continue;
             }
```

**Comment by Swizzy** [comment]
> @Swizzy I have managed to download the descriptions by modifying XboxAssetDownloader.cs, I suppose that the rest of the data can be obtained in the same way, I am going to continue working on it,
> To obtain the description I have done the following:
> 1st I added a Description property to the XboxTitleInfo class:
> 
> ```
> public class XboxTitleInfo {
>          public enum XboxAssetType {
>              Icon,
>              banner,
>              Background,
>              Screenshot
>          }
> 
>          public string Title { get; privateset; }
> 
>          // I added this string to get and assign the description
>          public string Description { get; privateset; }
> 
>          public string TitleId { get; privateset; }
> 
>          public string Locale { get; privateset; }
> 
>          public XboxAssetInfo[] AssetsInfo { get; privateset; }
> ```
> 
> 
> 2º I modified the ParseXml method to extract and assign the description:
> 
> ```
>         private static void ParseXml(Stream xmlData, XboxTitleInfo titleInfo) {
>             XboxAssetDownloader.SendStatusChanged("Parsing Title/Asset info...");
>             var ret = new List<XboxAssetInfo>();
>             using(var xml = XmlReader.Create(xmlData)) {
>                 while(xml.Read()) {
>                     if(!xml.IsStartElement())
>                         continue;
>                     if (xml.Name.ToLower() == "live:fulltitle") {
>                         xml.Read();
>                         titleInfo.Title = xml.Value;
>                         continue;
>                     }
> 
>                     // I added this code to get and assign the description
>                     if (xml.Name.ToLower() == "live:description") {
>                         xml.Read();
>                         titleInfo.Description = xml.Value;
>                         continue;
>                     }
> 
> ```

No need to update us on your progress with this tbh, but yes - that's basically all you do... add those things to parse out the info...

**Comment by JaviJJ117** [comment]
@Swizzy, okay, I just want to mention that I have decrypted Aurora and there are the original names to search for these elements although I have to change the capital letters so that they work in the code, there is more data than what I mentioned such as the maximum number of players offline, also in Systemlik and more things.
With this I have everything solved.
And I would like to know if you would be interested in me sharing the code with all the added data?
So you could add a new section to Aurora Asset Editor to get and display all the text data.

**Comment by Swizzy** [comment]
> @Swizzy, okay, I just want to mention that I have decrypted Aurora and there are the original names to search for these elements although I have to change the capital letters so that they work in the code, there is more data than what I mentioned such as the maximum number of players offline, also in Systemlik and more things. With this I have everything solved. And I would like to know if you would be interested in me sharing the code with all the added data? So you could add a new section to Aurora Asset Editor to get and display all the text data.

That functionality would rather belong to this project; https://github.com/XboxUnity/AuroraDbManager

**Comment by Swizzy** [comment]
Since we've agreed that the functionality is good now - i'll close this issue as fixed, i've updated the release i made to make it the latest version instead of a pre-release.
