### ISSUE TITLE
Unable to load DLL 'SQLite.Interop.dll':  HRESULT: 0x8007007E 

### ISSUE THREAD

**Issue by xjapn03** [XboxUnity/AuroraAssetEditor#13]
Its weird cause in the 1.3.1 version i can entablish connection and get all assets, but this updated v just entablished connection and throws that DLL error when im trying to get all assets.

(Aurora in the lastest version, correct ip)
(im trying to put autoboot psx games and change their cover to a customized one)

![Captura de pantalla 2024-01-04 182552](https://github.com/XboxUnity/AuroraAssetEditor/assets/128620330/26644a7b-0400-4c71-9da0-cc5c5d94be1e)

**Comment by Swizzy** [comment]
What version are you using when this happens? if you're using v1.4.1 something weird is going on
