### ISSUE TITLE
Aurora Asset Editor cannot download Elder Scrolls Online assets: 425307F8

### ISSUE THREAD

**Issue by JaviJJ117** [XboxUnity/AuroraAssetEditor#15]
Hello, I have seen that for this title it detects an Icon and a Banner but when selecting them the images cannot be downloaded, it keeps showing "Downloading asset data..."
I imagine that this problem will be reproduced in more titles, I would greatly appreciate it if you could solve this problem.

**Comment by Swizzy** [comment]
Most likely it means the resources aren't available anymore, not all resources linked by the XML is available unfortunately

**Comment by jrobiche** [comment]
Just confirmed, all of the fileUrl's for Elder Scrolls Online (425307F8) are 404
* http://avatar.xboxlive.com/global/t.425307f8/marketplace/0/1
* http://avatar.xboxlive.com/global/t.425307f8/icon/0/8000

**Comment by JaviJJ117** [comment]
Thanks for the clarification, I just saw that Aurora can't download the Banner either.

**Comment by JaviJJ117** [comment]
@jrobiche Please can you share the links of the backgrounds and Screenshots to download them from http://avatar.xboxlive.com/global/
I have seen that with the "354807DC / MX VS ATV Supercross" Icon you get a different image than with Aurora Asset Editor, I have also seen that the Banner is the same and of the same quality but from avatar.xboxlive.com it takes up less space, I would be very grateful if you would share the links so I can make a complete download of those assets.

**Comment by Swizzy** [comment]
> @jrobiche Please can you share the links of the backgrounds and Screenshots to download them from http://avatar.xboxlive.com/global/
> I have seen that with the "354807DC / MX VS ATV Supercross" Icon you get a different image than with Aurora Asset Editor, I have also seen that the Banner is the same and of the same quality but from avatar.xboxlive.com it takes up less space, I would be very grateful if you would share the links so I can make a complete download of those assets.

If they are available there, they should be linked in the XML, there is no standard transformation rule

**Comment by jrobiche** [comment]
I am not aware of any covers, backgrounds, screenshots, etc... on avatar.xboxlive.com
That domain is mainly used to host gamer pictures and avatar item images so I'm not really sure why Microsoft decided to host icons and banners on that domain

**Comment by JaviJJ117** [comment]
> > @jrobiche Please can you share the links of the backgrounds and Screenshots to download them from http://avatar.xboxlive.com/global/
> > I have seen that with the "354807DC / MX VS ATV Supercross" Icon you get a different image than with Aurora Asset Editor, I have also seen that the Banner is the same and of the same quality but from avatar.xboxlive.com it takes up less space, I would be very grateful if you would share the links so I can make a complete download of those assets.
> 
> If they are available there, they should be linked in the XML, there is no standard transformation rule

It is strange but in this case the Icons are totally different images, I wanted to comment that I have seen that the Boxart (The covers from the marketplace) can be downloaded, you have to set the value 33 in imageRelationshipType to obtain those Assets, modify the AuroraAssetEditor code to be able to downloading these images, I see it useful to later create personalized covers for arcade and Indie games, I think it would not be a bad idea to implement the download of these Assets in the Aurora Asset Editor application.

**Comment by Swizzy** [comment]
That would require image editing capabilities to be implemented aswell as the cover art from the Xbox Marketplace only has 2 parts; Front and Back, as separate images while Aurora needs the full cover (Front + Spine + Back) in a specific size, if the covers from the Xbox Marketplace are different dimensions from what Aurora expects the front/back to be, this wouldn't work as nicely, scaling could be done to force them to fit, but - that'd make the final result really bad.

Unfortunately for now, this isn't going to happen, eventually maybe someone will do this? but it seems unlikely at this point in time.

**Comment by JaviJJ117** [comment]
> That would require image editing capabilities to be implemented aswell as the cover art from the Xbox Marketplace only has 2 parts; Front and Back, as separate images while Aurora needs the full cover (Front + Spine + Back) in a specific size as a single image, if the covers from the Xbox Marketplace are different dimensions from what Aurora expects the front/back to be, this wouldn't work as nicely, scaling could be done to force them to fit, but - that'd make the final result really bad.
> 
> Unfortunately for now, this isn't going to happen, eventually maybe someone will do this? but it seems unlikely at this point in time.

@Swizzy At the moment I would like to be able to add the back to download absolutely all the images, I imagine that they can be used in the future I still think that many images of XBLA and XBLIG games have their Unity covers from these some are as you say It shows that they do not have much resolution, I have only been able to locate the Front and I have seen that it is the value 33, do you know what the value of the back is? I don't remember seeing those images in the marketplace on PC or Xbox.

**Comment by Swizzy** [comment]
You may make your own application downloading and saving any and all images from the Marketplace - the code for downloading this information is easily found in the repo. Saving the downloaded data is as easy as using this method: https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writeallbytes?view=netframework-4.8

The purpose of Aurora Asset Editor is NOT to archive data, it's to manage assets used by Aurora in the form of Covers, Backgrounds, Icons, Banners etc.

Please don't make further requests to me or jrobiche asking to add features purely for the sake of archiving images etc. We have already done a massive job of archiving alot of stuff which we're going to be going through and cleaning up at some point in time. There are also plans of making a offline package available for Aurora Asset Editor or to create a replacement for the marketplace once it's shutdown for good.

**Comment by JaviJJ117** [comment]
@Swizzy Okay, I will not make any more requests to add functionalities to Aurora Asset Editor, I already have an application created with which I can download all the images of the assets completely from a complete list of the available IDs that I obtained by creating another application with XboxAssetEditor. cs, I think the only thing I would be missing is the back of the cover that you mentioned before, if it is available in the marketplace, are you sure about this? Thank you for sharing the information to create my own application, but what I need the information about the assets in the API to see what the value of the back of the boxart is.
I am very happy to know that you still have plans to preserve and manage the marketplace information. Will this bring with it all the text of each region and the trailers? I am worried that there will not be enough time to do everything, which is why I am working on extracting this information. directly with Aurora on xbox right now.

**Comment by Swizzy** [comment]
I believe there used to be the back of them, maybe not - the front i know for sure. We haven't really done any filtering on the images saved, we save all available images as-is and go through them later

It will not include trailers because those aren't used and have a very tricky setup to save the actual video itself.

We've archived all of the text and metadata already for every possible region/locale, i believe we also have most if not all of the images aswell.

**Comment by JaviJJ117** [comment]
Thank you, that reassures me a lot, one of the things that worried me the most was losing all the information in text for my region, if it is of any use to the project I can share the list of the 8,035 Title Ids available in the API in the locale en-US I don't know if they have compiled the information on all of them, it seems to me that all the XBLIGs are there.
I have seen that some images vary depending on the locale, for example those of Halo Combat evolvet are different in ja-JP, also those of Cars and Halo 3 ODST also change between en-US and other localities, that is why I am trying to download everything to all premises.
