### ISSUE TITLE
Xbox.com error

### ISSUE THREAD

**Issue by FlamezMain** [XboxUnity/AuroraAssetEditor#19]
I use xboxunity for the game covers, but when i switch to xbox.com for the things like background and banners, it shows that an error has occured.

[2024/06/22 15:55:47]:
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraAssetEditor.Classes.XboxAssetDownloader.GetTitleInfo(String keywords, XboxLocale locale) in C:\projects\auroraasseteditor\AuroraAssetEditor\Classes\XboxAssetDownloader.cs:line 40
   at AuroraAssetEditor.Controls.OnlineAssetsControl.<.ctor>b__19_5(Object sender, DoWorkEventArgs args) in C:\projects\auroraasseteditor\AuroraAssetEditor\Controls\OnlineAssetsControl.xaml.cs:line 108

**Comment by Swizzy** [comment]
Most likely the issue is that the response didn't contain the expected response.

The reason that would happen is that Microsoft changed the way the API works or completely shut it down now, the later is expected to happen soon if it hasn't already.

**Comment by FlamezMain** [comment]
> Microsoft changed the way the API works or completely shut it down now,

If what you say is true, then I might be unable to get anything other than covers. Thanks for telling me what could've been the reason.

**Comment by Swizzy** [comment]
> > Microsoft changed the way the API works or completely shut it down now,
> 
> If what you say is true, then I might be unable to get anything other than covers. Thanks for telling me what could've been the reason.

Everything has been archived by the community, we just need to complete setting things up in a useable format

**Comment by Swizzy** [comment]
I did some quick checks now with the API that should be involved in this case - and that is still working as intended when used with Chrome, examples;

Searching for "GTA" using the "en-us" locale; https://marketplace.xbox.com/en-us/SiteSearch/xbox/?query=GTA&PageSize=5
Searching for a empty string using the "en-us" locale; https://marketplace.xbox.com/en-us/SiteSearch/xbox/?query=&PageSize=5

Would you mind letting us know which locale you were using and what you were searching for? that may help figure out what the problem is so it can be fixed.

**Comment by FlamezMain** [comment]
I was trying different games when searching, but I noticed now for whatever reason locale is blank and I don't know if it is because i'm using a bad pc or what.
![image](https://github.com/XboxUnity/AuroraAssetEditor/assets/173553600/b8801582-ca99-4a5e-a6c3-2dbd499d6bb9)

**Comment by Swizzy** [comment]
Please update to the latest version and see if it works as it should?; https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.4.2

**Comment by FlamezMain** [comment]
My version was the latest so I redownloaded it and now it is working as it should. I apologize for wasting your time as I am still fairly new to these type of things.

**Comment by Swizzy** [comment]
You were using version 1.3 according to the titlebar in the screenshot, the latest version as of this writing is 1.4.2 the one i linked you to.
