### ISSUE TITLE
Errors in latest version

### ISSUE THREAD

**Issue by zakrpa** [XboxUnity/AuroraAssetEditor#9]
Hello,

Connection works fine but when trying to click get assets getting error and to check log file.
[error.log](https://github.com/XboxUnity/AuroraAssetEditor/files/13055431/error.log)

Update:
Downloaded source code and did publish / compile again seems like VS create 2 separate folders with app (I m noob at coding so I m trying to explain)

```
_bin/Release/net48_
This folder contains x64 and x86 folder with SQLite.Interop.dll file
**Executing app from this net48 folder runs fine without any error**

_bin/Release/net48/publish_ 
This folder is like app which I download from site missing this two x64 and x86 folder
**Executing app from this folder gives errors...** 
```

_**The most important is that my older version which worked like 15 days or month ago cant remember worked just fine. Same errors getting using older version (so yea not only in new version my mistake). Possible windows update did something or maybe me. Cant  remember that I made some system changes install / uninstalls to cause error.**_

**Comment by Swizzy** [comment]
The main error in the log talks about the missing SQLite dlls, we'll look into why those aren't included in the publish and fix the problem.

**Comment by Buleste** [comment]
Different but similar issue.
I cannot connect to my Xbox 360 via ftp and the error log shows 

> [23/10/2023 21:53:12]:
System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at AuroraAssetEditor.Classes.AuroraDbManager.ConnectToContent(String path) in C:\projects\auroraasseteditor\AuroraAssetEditor\Classes\AuroraDbManager.cs:line 24
   at AuroraAssetEditor.Classes.AuroraDbManager.GetDbTitles(String path) in C:\projects\auroraasseteditor\AuroraAssetEditor\Classes\AuroraDbManager.cs:line 42
   at AuroraAssetEditor.Controls.FtpAssetsControl.<GetAssetsClick>b__13_0(Object o, DoWorkEventArgs args) in C:\projects\auroraasseteditor\AuroraAssetEditor\Controls\FtpAssetsControl.xaml.cs:line 97

**Comment by zakrpa** [comment]
> Different but similar issue. I cannot connect to my Xbox 360 via ftp and the error log shows
> 
> > [23/10/2023 21:53:12]:
> > System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> > at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
> > at System.Data.SQLite.SQLite3.StaticIsInitialized()
> > at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
> > at System.Data.SQLite.SQLiteLog.Initialize(String className)
> > at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
> > at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
> > at AuroraAssetEditor.Classes.AuroraDbManager.ConnectToContent(String path) in C:\projects\auroraasseteditor\AuroraAssetEditor\Classes\AuroraDbManager.cs:line 24
> > at AuroraAssetEditor.Classes.AuroraDbManager.GetDbTitles(String path) in C:\projects\auroraasseteditor\AuroraAssetEditor\Classes\AuroraDbManager.cs:line 42
> > at AuroraAssetEditor.Controls.FtpAssetsControl.b__13_0(Object o, DoWorkEventArgs args) in C:\projects\auroraasseteditor\AuroraAssetEditor\Controls\FtpAssetsControl.xaml.cs:line 97

I did have maybe same errors but depends what u try to do... After recompile source code in VS and now works. Cant attach 2 folders or files here which u need its not supported.

**Comment by Swizzy** [comment]
It should be working with the latest release: https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.4.1 can one of you guys download it and see if it works properly for you?

Unfortunately i'm not entirely sure how to add the extra step in the publish in VS - but, AppVeyor allows me to do whatever i want with the build prior to uploading to github.

**Comment by Buleste** [comment]
That works perfectly for me. Thank you

**Comment by Swizzy** [comment]
I'm willing to call this issue resolved then - could you @zakrpa confirm that it works for you aswell? if not - we're going to need fresh logs with this build to understand what the issue is exactly - preferably clean logs with only 1 attempt at running things.

You must extract ALL files and folders and not simply hitting "run" for things to really work tho - if you don't it's likely that only the exe is extracted which would lead to the same issue again as the file isn't where it's expected to be.

**Comment by zakrpa** [comment]
Oh everything seems ok, I will close ticket.

Thank u very much
